[general]
render_method = "model"
model = "model/model.bin"
glyphs = [
  " ", "!", "\"", "#", "$", "%", "&", "'", "(", ")", "*", "+", ",", "-", ".", "/", 
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ":", ";", "<", "=", ">", "?", 
  "@", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", 
  "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "[", "\\", "]", "^", "_", 
  "`", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", 
  "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "{", "|", "}", "~"
]

[ssim]
tile_size = 8
subdivide = 2
font = "assets/CascadiaMono.ttf"

[training]
learning_rate = 0.05
hidden_layers = 1
hidden_neurons = 64
alpha = 0.075
l2 = 0.075
adam_beta1 = 0.9
adam_beta2 = 0.999
batch_size = 2048
checkpoint_period = 100