[package]
name = "utils"
version = "0.0.1"
edition = "2021"

[dependencies]
imageproc = "0.25.0"
toml = "0.8.15"
serde = { version = "1.0.204", features = ["derive"] }
nalgebra = "0.33.0"

[lib]
name = "utils"