[package]
name = "libi2a"
version = "0.0.1"
edition = "2021"

[dependencies]
imageproc = "0.25.0"
ab_glyph = "0.2"
rayon = "1.10.0"
nalgebra = "0.33.0"
rand = "0.8.5"
rand_distr = "0.4.3"
utils = { path = "../utils" }

[lib]
name = "libi2a"