[general]
render_method = "ssim"
glyphs = [
    " ",
    "░",
    "█"
]

[ssim]
tile_size = 8
subdivide = 2
font = "assets/CascadiaMono.ttf"

[training]
learning_rate = 0.01
hidden_layers = 0
hidden_neurons = 1
alpha = 0.01
l2 = 0.01
adam_beta1 = 0.9
adam_beta2 = 0.999
batch_size = 1